name: release-to-maven-central
on:
  workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Releasing to Maven Central"

      - uses: actions/checkout@v2

      - name: Set up settings.xml for Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Remove SNAPSHOT from versions
        run: mvn versions:set -DremoveSnapshot=true versions:commit --no-transfer-progress

      - name: Publish to Central
        run: mvn --batch-mode clean deploy --no-transfer-progress -P central-deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
            
      - name: Get version
        id: get_version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=VERSION::$VERSION"

      - name: Commit release version
        uses: EndBug/add-and-commit@v7
        with:
          message: Released v${{ steps.get_version.outputs.VERSION }}

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: v${{ steps.get_version.outputs.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: |
            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Increment to next SNAPSHOT version
        run: mvn versions:set -DnextSnapshot=true versions:commit --no-transfer-progress

      - name: Get next snapshot version
        id: get_next_snapshot_version
        run: |
          NEXT_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=NEXT_VERSION::$NEXT_VERSION"

      - name: Commit next SNAPSHOT version
        uses: EndBug/add-and-commit@v7
        with:
          message: Incremented to snapshot v${{ steps.get_next_snapshot_version.outputs.NEXT_VERSION }}
